name: autopve

services:
  autopve:
    image: localhost/autopve:latest
    build: .
    ports:
      - ${AUTOPVE_PORT:-8080}:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${AUTOPVE_DATA_PATH:-~/path/to/data}:/app/data
      - ${AUTOPVE_LOGS_PATH:-~/path/to/logs}:/app/logs
    environment:
      - PUID=${AUTOPVE_PUID:-1000}
      - PGID=${AUTOPVE_PGID:-1000}
      - VERBOSE_LOGGING=${AUTOPVE_VERBOSE_LOGGING:-TRUE} # Optional
      - SSH_KEY_TYPE=${AUTOPVE_SSH_KEY_TYPE:-rsa} # Optional
